# 비밀(AES/JWT/외부 API키 등을 모아둔 장소)
spring.profiles.include=secret

# 1. Server Configuration
server.port=8080
server.servlet.context-path=/


# 2. Oracle Database Configuration (설계도 반영)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# @localhost:1521:xe 부분은 본인의 DB 환경에 맞춰 수정이 필요할 수 있습니다.
spring.datasource.url=jdbc:oracle:thin:@//14.54.128.146:1521/XE
spring.datasource.username=lawyer_dev
spring.datasource.password=lawyer1234

# 3. MyBatis Configuration (DAO 패턴 필수 설정)
# SQL이 작성될 XML 파일의 위치를 지정합니다.
mybatis.mapper-locations=classpath:mapper/**/*.xml
# DB의 snake_case(user_id)를 Java의 camelCase(userId)로 자동 변환해줍니다. (실무 필수)
mybatis.configuration.map-underscore-to-camel-case=true
# 매퍼에서 사용할 DTO들의 기본 패키지 경로를 지정합니다.
mybatis.type-aliases-package=com.example.backend_main.dto

# 4. Security & JWT Configuration
# 보안을 위해 세션을 사용하지 않고 Stateless 방식으로 운영합니다.
spring.main.allow-bean-definition-overriding=true

# 5. File Upload Configuration (Apache POI 활용 대비)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 6. Logging Configuration (개발/디버깅용)
# SQL 쿼리문이 콘솔에 보이도록 설정합니다. (이새끼 좀 치네 포인트)
logging.level.com.example.backendmain.dao=debug
logging.level.org.springframework.security=info

# 7. AES-256 (금고의 실물 열쇠) - 32자(256비트/8 = 32) - 영문 기준 정확히 32글자(~31 / 33~ 일 경우 에러)
# 데이터베이스(DB)에 저장되는 실제 정보를 잠그고 풀 때 사용
encryption.aes256.key=${encryption.aes256.key}
# 8. JWT 토큰 뒷부분에 디지털 서명 남기기 - 신분증의 출처를 증명하는 용도
jwt.secret=${jwt.secret}