# 1. Server Configuration
server.port=8080
server.servlet.context-path=/

# 2. Oracle Database Configuration (??? ??)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# @localhost:1521:xe ??? ??? DB ??? ?? ??? ??? ? ????.
spring.datasource.url=jdbc:oracle:thin:@192.168.0.43:1521/XE
spring.datasource.username=fourjo
spring.datasource.password=4444

# 3. MyBatis Configuration (DAO ?? ?? ??)
# SQL? ??? XML ??? ??? ?????.
#mybatis.mapper-locations=classpath:mapper/**/*.xml
# DB? snake_case(user_id)? Java? camelCase(userId)? ?? ??????. (?? ??)
mybatis.configuration.map-underscore-to-camel-case=true
# ???? ??? DTO?? ?? ??? ??? ?????.
mybatis.type-aliases-package=com.example.backend_main.dto

# 4. Security & JWT Configuration
# ??? ?? ??? ???? ?? Stateless ???? ?????.
spring.main.allow-bean-definition-overriding=true

# 5. File Upload Configuration (Apache POI ?? ??)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 6. Logging Configuration (??/????)
# SQL ???? ??? ???? ?????. (??? ? ?? ???)
logging.level.com.example.backendmain.dao=debug
logging.level.org.springframework.security=info