# 1. AES-256 ???? ??? ? (??? 32??? ???)
encryption.aes256.key=LawGuardianProjectSecretKey2026!
encryption.aes256.old-key=thisIsExactlyThirtyTwoCharacters
# 2. JWT ??? ?? ? (??? ?? 32? ??? ? ???? ?????)
# ?? ? : this-is-a-very-long-secret-key-
jwt.secret=thisIsAVeryLongAndSecureSecretKeyForLawGuardian2026Project